### docker-compose.yml
version: '3.8'

services:
  student-iep:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/studentIEP
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - student-iep
    command: npm start

volumes:
  mongo_data:

